Sprint 1
kDallas1203/middle.messenger.praktikum.yandex pull request #1
Opened 2022-11-29 20:18 UTC by kDallas1203

2022-12-06 10:49 UTC, podlovchenko requested changes
Привет, в целом все хорошо, оставила несколько некритичных комментариев, добавь, пожалуйста ссылки на макеты и нетлифай в ридми

2022-12-06 10:49 UTC, podlovchenko commented on .parcelrc
> +}
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-12-06 10:49 UTC, podlovchenko commented on package.json
> +    "normalize.css": "^8.0.1"
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2022-12-06 10:49 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-12-06 10:49 UTC, podlovchenko commented on serve.js
> +const port = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-12-07 08:44 UTC, podlovchenko commented on README.md
> +Ссылка на проект: https://practic-chat.netlify.app
По ссылке сейчас page not found

2022-12-08 08:03 UTC, kDallas1203 commented on README.md
> +Ссылка на проект: https://practic-chat.netlify.app
Пофиксил

2022-12-08 08:42 UTC, podlovchenko commented
Работу принимаю

2022-12-13 12:54 UTC, merged